org.gradle.caching=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.tooling.parallel=true

########## Properties for publishing to Maven Central ##########

GROUP=io.github.goooler.mmkv
VERSION_NAME=2.2.4-SNAPSHOT

mavenCentralAutomaticPublishing=true
mavenCentralDeploymentValidation=NONE
mavenCentralPublishing=true
signAllPublications=true

POM_NAME=MMKV Android
POM_DESCRIPTION=Patch Tencent/MMKV to add 32-bit support.
POM_INCEPTION_YEAR=2025
POM_URL=https://github.com/Goooler/MMKV

POM_LICENSE_NAME=BSD-3-Clause
POM_LICENSE_URL=https://opensource.org/license/bsd-3-clause
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/Goooler/MMKV
POM_SCM_CONNECTION=scm:git:git://github.com/Goooler/MMKV.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/Goooler/MMKVgit

POM_DEVELOPER_ID=goooler
POM_DEVELOPER_NAME=Zongle Wang
POM_DEVELOPER_URL=https://github.com/Goooler
